using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EMutabakat.Migrations
{
    /// <inheritdoc />
    public partial class ChangeCurrentCompositeKeyAndImport : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Mutabakatlar_Cariler_CariId",
                table: "Mutabakatlar");

            migrationBuilder.DropIndex(
                name: "IX_Mutabakatlar_CariId",
                table: "Mutabakatlar");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Cariler",
                table: "Cariler");

            migrationBuilder.Sql("ALTER TABLE \"Cariler\" ALTER COLUMN \"CariId\" DROP IDENTITY IF EXISTS;");
            migrationBuilder.Sql("ALTER TABLE \"Cariler\" ALTER COLUMN \"CariId\" TYPE text USING \"CariId\"::text;");
            migrationBuilder.Sql("ALTER TABLE \"Mutabakatlar\" ALTER COLUMN \"CariId\" TYPE text USING \"CariId\"::text;");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Cariler",
                table: "Cariler",
                columns: new[] { "CariId", "FirmaId" });

            migrationBuilder.CreateIndex(
                name: "IX_Mutabakatlar_CariId_FirmaId",
                table: "Mutabakatlar",
                columns: new[] { "CariId", "FirmaId" });

            migrationBuilder.AddForeignKey(
                name: "FK_Mutabakatlar_Cariler_CariId_FirmaId",
                table: "Mutabakatlar",
                columns: new[] { "CariId", "FirmaId" },
                principalTable: "Cariler",
                principalColumns: new[] { "CariId", "FirmaId" },
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Mutabakatlar_Cariler_CariId_FirmaId",
                table: "Mutabakatlar");

            migrationBuilder.DropIndex(
                name: "IX_Mutabakatlar_CariId_FirmaId",
                table: "Mutabakatlar");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Cariler",
                table: "Cariler");

            migrationBuilder.Sql("ALTER TABLE \"Mutabakatlar\" ALTER COLUMN \"CariId\" TYPE integer USING \"CariId\"::integer;");
            migrationBuilder.Sql("ALTER TABLE \"Cariler\" ALTER COLUMN \"CariId\" TYPE integer USING \"CariId\"::integer;");
            migrationBuilder.Sql("ALTER TABLE \"Cariler\" ALTER COLUMN \"CariId\" ADD GENERATED BY DEFAULT AS IDENTITY;");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Cariler",
                table: "Cariler",
                column: "CariId");

            migrationBuilder.CreateIndex(
                name: "IX_Mutabakatlar_CariId",
                table: "Mutabakatlar",
                column: "CariId");

            migrationBuilder.AddForeignKey(
                name: "FK_Mutabakatlar_Cariler_CariId",
                table: "Mutabakatlar",
                column: "CariId",
                principalTable: "Cariler",
                principalColumn: "CariId",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
