using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EMutabakat.Migrations
{
    /// <inheritdoc />
    public partial class ConvertUserIdToIdentityInt : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_KullaniciYetkileri_Kullanicilar_KullaniciId",
                table: "KullaniciYetkileri");

            migrationBuilder.DropForeignKey(
                name: "FK_KullaniciFirmalar_Kullanicilar_KullaniciId",
                table: "KullaniciFirmalar");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Kullanicilar",
                table: "Kullanicilar");

            migrationBuilder.DropIndex(
                name: "IX_KullaniciFirmalar_KullaniciId_FirmaId",
                table: "KullaniciFirmalar");

            migrationBuilder.Sql(@"ALTER TABLE ""KullaniciFirmalar"" ALTER COLUMN ""KullaniciId"" TYPE integer USING ""KullaniciId""::integer;");
            migrationBuilder.Sql(@"ALTER TABLE ""KullaniciYetkileri"" ALTER COLUMN ""KullaniciId"" TYPE integer USING ""KullaniciId""::integer;");
            migrationBuilder.Sql(@"ALTER TABLE ""Kullanicilar"" ALTER COLUMN ""KullaniciId"" TYPE integer USING ""KullaniciId""::integer;");
            migrationBuilder.Sql(@"ALTER TABLE ""Kullanicilar"" ALTER COLUMN ""KullaniciId"" ADD GENERATED BY DEFAULT AS IDENTITY;");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Kullanicilar",
                table: "Kullanicilar",
                column: "KullaniciId");

            migrationBuilder.CreateIndex(
                name: "IX_KullaniciFirmalar_KullaniciId_FirmaId",
                table: "KullaniciFirmalar",
                columns: new[] { "KullaniciId", "FirmaId" },
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "FK_KullaniciYetkileri_Kullanicilar_KullaniciId",
                table: "KullaniciYetkileri",
                column: "KullaniciId",
                principalTable: "Kullanicilar",
                principalColumn: "KullaniciId",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_KullaniciFirmalar_Kullanicilar_KullaniciId",
                table: "KullaniciFirmalar",
                column: "KullaniciId",
                principalTable: "Kullanicilar",
                principalColumn: "KullaniciId",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_KullaniciYetkileri_Kullanicilar_KullaniciId",
                table: "KullaniciYetkileri");

            migrationBuilder.DropForeignKey(
                name: "FK_KullaniciFirmalar_Kullanicilar_KullaniciId",
                table: "KullaniciFirmalar");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Kullanicilar",
                table: "Kullanicilar");

            migrationBuilder.DropIndex(
                name: "IX_KullaniciFirmalar_KullaniciId_FirmaId",
                table: "KullaniciFirmalar");

            migrationBuilder.Sql(@"ALTER TABLE ""Kullanicilar"" ALTER COLUMN ""KullaniciId"" DROP IDENTITY IF EXISTS;");
            migrationBuilder.Sql(@"ALTER TABLE ""Kullanicilar"" ALTER COLUMN ""KullaniciId"" TYPE text USING ""KullaniciId""::text;");
            migrationBuilder.Sql(@"ALTER TABLE ""KullaniciYetkileri"" ALTER COLUMN ""KullaniciId"" TYPE text USING ""KullaniciId""::text;");
            migrationBuilder.Sql(@"ALTER TABLE ""KullaniciFirmalar"" ALTER COLUMN ""KullaniciId"" TYPE text USING ""KullaniciId""::text;");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Kullanicilar",
                table: "Kullanicilar",
                column: "KullaniciId");

            migrationBuilder.CreateIndex(
                name: "IX_KullaniciFirmalar_KullaniciId_FirmaId",
                table: "KullaniciFirmalar",
                columns: new[] { "KullaniciId", "FirmaId" },
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "FK_KullaniciYetkileri_Kullanicilar_KullaniciId",
                table: "KullaniciYetkileri",
                column: "KullaniciId",
                principalTable: "Kullanicilar",
                principalColumn: "KullaniciId",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_KullaniciFirmalar_Kullanicilar_KullaniciId",
                table: "KullaniciFirmalar",
                column: "KullaniciId",
                principalTable: "Kullanicilar",
                principalColumn: "KullaniciId",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
