// <auto-generated />
using System;
using EMutabakat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EMutabakat.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507073923_AddActivePassiveToCurrencyCodes")]
    partial class AddActivePassiveToCurrencyCodes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EMutabakat.Models.AppLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("AppLogs");
                });

            modelBuilder.Entity("EMutabakat.Models.Cari", b =>
                {
                    b.Property<string>("CariId")
                        .HasColumnType("text");

                    b.Property<int>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<string>("CariAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CariAdres")
                        .HasColumnType("text");

                    b.Property<int>("CariAktifPasif")
                        .HasColumnType("integer");

                    b.Property<string>("CariDovizKodu")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CariGrupId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CariIl")
                        .HasColumnType("text");

                    b.Property<string>("CariIlce")
                        .HasColumnType("text");

                    b.Property<string>("CariUnvan")
                        .HasColumnType("text");

                    b.Property<string>("CariVergiDairesi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("CariVergiNumarasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CariWebAdresi")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("CariYetkiliAdiSoyadi")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CariYetkiliGsm")
                        .HasColumnType("text");

                    b.Property<string>("CariYetkiliMail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CariYetkiliTelefon")
                        .HasColumnType("text");

                    b.HasKey("CariId", "FirmaId");

                    b.HasIndex("CariDovizKodu");

                    b.HasIndex("CariGrupId");

                    b.HasIndex("FirmaId", "CariAdi")
                        .IsUnique();

                    b.ToTable("Cariler");
                });

            modelBuilder.Entity("EMutabakat.Models.CariGrup", b =>
                {
                    b.Property<string>("CariGrupId")
                        .HasColumnType("text");

                    b.Property<string>("CariGrupAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CariGrupAktifPasif")
                        .HasColumnType("integer");

                    b.Property<int>("FirmaId")
                        .HasColumnType("integer");

                    b.HasKey("CariGrupId");

                    b.HasIndex("FirmaId");

                    b.ToTable("CariGruplar");
                });

            modelBuilder.Entity("EMutabakat.Models.DovizKodu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DovizKoduAktifPasif")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TCMB")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("DovizKodlari");
                });

            modelBuilder.Entity("EMutabakat.Models.Firma", b =>
                {
                    b.Property<int>("FirmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FirmaId"));

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FirmaAdres")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("FirmaAktifPasif")
                        .HasColumnType("integer");

                    b.Property<string>("FirmaGsm")
                        .HasColumnType("text");

                    b.Property<string>("FirmaIl")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirmaIlce")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirmaMail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FirmaMersisNumarasi")
                        .HasColumnType("text");

                    b.Property<string>("FirmaSmtpHost")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FirmaSmtpPassword")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("FirmaSmtpPort")
                        .HasColumnType("integer");

                    b.Property<string>("FirmaSmtpSecure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmaSmtpUser")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FirmaTelefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmaUnvan")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("FirmaVergiDairesi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FirmaVergiNumarasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmaWebAdresi")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("FirmaYetkiliAdiSoyadi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("FirmaId");

                    b.ToTable("Firmalar");
                });

            modelBuilder.Entity("EMutabakat.Models.Kullanici", b =>
                {
                    b.Property<string>("KullaniciId")
                        .HasColumnType("text");

                    b.Property<bool>("IsSeedUser")
                        .HasColumnType("boolean");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("KullaniciAktifPasif")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KullaniciGsm")
                        .HasColumnType("text");

                    b.Property<string>("KullaniciMail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("KullaniciSoyadi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Sifre")
                        .HasColumnType("text");

                    b.HasKey("KullaniciId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("EMutabakat.Models.KullaniciYetki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CariGruplar")
                        .HasColumnType("integer");

                    b.Property<int>("Cariler")
                        .HasColumnType("integer");

                    b.Property<int>("DovizKodlari")
                        .HasColumnType("integer");

                    b.Property<bool>("ExportYetki")
                        .HasColumnType("boolean");

                    b.Property<int>("Firmalar")
                        .HasColumnType("integer");

                    b.Property<bool>("ImportYetki")
                        .HasColumnType("boolean");

                    b.Property<string>("KullaniciId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Kullanicilar")
                        .HasColumnType("integer");

                    b.Property<bool>("LogYetki")
                        .HasColumnType("boolean");

                    b.Property<int>("Mutabakatlar")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId")
                        .IsUnique();

                    b.ToTable("KullaniciYetkileri");
                });

            modelBuilder.Entity("EMutabakat.Models.Mutabakat", b =>
                {
                    b.Property<int>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<string>("CariId")
                        .HasColumnType("text");

                    b.Property<DateTime>("MutabakatTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MutabakatAciklama")
                        .HasColumnType("text");

                    b.Property<decimal>("MutabakatBakiye")
                        .HasColumnType("numeric");

                    b.Property<string>("MutabakatBakiyeTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MutabakatCevapAciklama")
                        .HasColumnType("text");

                    b.Property<string>("MutabakatCevapAdSoyad")
                        .HasColumnType("text");

                    b.Property<string>("MutabakatCevapGsm")
                        .HasColumnType("text");

                    b.Property<string>("MutabakatCevapMail")
                        .HasColumnType("text");

                    b.Property<DateTime?>("MutabakatCevapTarihSaat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MutabakatDovizKodu")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("MutabakatGonderimTarihSaat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MutabakatId")
                        .HasColumnType("text");

                    b.Property<string>("MutabakatReceiveStoragePath")
                        .HasColumnType("text");

                    b.Property<string>("MutabakatToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("FirmaId", "CariId", "MutabakatTarihi");

                    b.HasIndex("MutabakatDovizKodu");

                    b.HasIndex("MutabakatId")
                        .IsUnique();

                    b.HasIndex("CariId", "FirmaId");

                    b.ToTable("Mutabakatlar");
                });

            modelBuilder.Entity("EMutabakat.Models.SilinenMutabakat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CariId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<string>("MutabakatAciklama")
                        .HasColumnType("text");

                    b.Property<decimal>("MutabakatBakiye")
                        .HasColumnType("numeric");

                    b.Property<string>("MutabakatBakiyeTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MutabakatCevapAciklama")
                        .HasColumnType("text");

                    b.Property<string>("MutabakatCevapAdSoyad")
                        .HasColumnType("text");

                    b.Property<string>("MutabakatCevapGsm")
                        .HasColumnType("text");

                    b.Property<string>("MutabakatCevapMail")
                        .HasColumnType("text");

                    b.Property<DateTime?>("MutabakatCevapTarihSaat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MutabakatDovizKodu")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("MutabakatGonderimTarihSaat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MutabakatId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MutabakatReceiveStoragePath")
                        .HasColumnType("text");

                    b.Property<DateTime>("MutabakatTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MutabakatToken")
                        .HasColumnType("text");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MutabakatDovizKodu");

                    b.HasIndex("CariId", "FirmaId");

                    b.HasIndex("FirmaId", "CariId", "MutabakatTarihi");

                    b.ToTable("SilinenMutabakatlar");
                });

            modelBuilder.Entity("KullaniciFirmalar", b =>
                {
                    b.Property<int>("KullaniciFirmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("KullaniciFirmaId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KullaniciFirmaId"));

                    b.Property<int>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<string>("KullaniciId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("KullaniciFirmaId");

                    b.HasIndex("FirmaId");

                    b.HasIndex("KullaniciId", "FirmaId")
                        .IsUnique();

                    b.ToTable("KullaniciFirmalar", (string)null);
                });

            modelBuilder.Entity("EMutabakat.Models.Cari", b =>
                {
                    b.HasOne("EMutabakat.Models.DovizKodu", "DovizKodu")
                        .WithMany()
                        .HasForeignKey("CariDovizKodu")
                        .HasPrincipalKey("TCMB")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMutabakat.Models.CariGrup", "CariGrup")
                        .WithMany()
                        .HasForeignKey("CariGrupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMutabakat.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CariGrup");

                    b.Navigation("DovizKodu");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("EMutabakat.Models.CariGrup", b =>
                {
                    b.HasOne("EMutabakat.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("EMutabakat.Models.KullaniciYetki", b =>
                {
                    b.HasOne("EMutabakat.Models.Kullanici", "Kullanici")
                        .WithOne("Yetkileri")
                        .HasForeignKey("EMutabakat.Models.KullaniciYetki", "KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("EMutabakat.Models.Mutabakat", b =>
                {
                    b.HasOne("EMutabakat.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMutabakat.Models.DovizKodu", "DovizKodu")
                        .WithMany()
                        .HasForeignKey("MutabakatDovizKodu")
                        .HasPrincipalKey("TCMB")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMutabakat.Models.Cari", "Cari")
                        .WithMany()
                        .HasForeignKey("CariId", "FirmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cari");

                    b.Navigation("DovizKodu");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("EMutabakat.Models.SilinenMutabakat", b =>
                {
                    b.HasOne("EMutabakat.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMutabakat.Models.DovizKodu", "DovizKodu")
                        .WithMany()
                        .HasForeignKey("MutabakatDovizKodu")
                        .HasPrincipalKey("TCMB")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMutabakat.Models.Cari", "Cari")
                        .WithMany()
                        .HasForeignKey("CariId", "FirmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cari");

                    b.Navigation("DovizKodu");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("KullaniciFirmalar", b =>
                {
                    b.HasOne("EMutabakat.Models.Firma", null)
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMutabakat.Models.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EMutabakat.Models.Kullanici", b =>
                {
                    b.Navigation("Yetkileri")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
