using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EMutabakat.Migrations
{
    /// <inheritdoc />
    public partial class ChangeCariGrupIdToString : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Cariler_CariGruplar_CariGrupId",
                table: "Cariler");

            migrationBuilder.Sql("ALTER TABLE \"CariGruplar\" ALTER COLUMN \"CariGrupId\" DROP IDENTITY IF EXISTS;");
            migrationBuilder.Sql("ALTER TABLE \"CariGruplar\" ALTER COLUMN \"CariGrupId\" TYPE text USING \"CariGrupId\"::text;");
            migrationBuilder.Sql("ALTER TABLE \"Cariler\" ALTER COLUMN \"CariGrupId\" TYPE text USING \"CariGrupId\"::text;");

            migrationBuilder.AddForeignKey(
                name: "FK_Cariler_CariGruplar_CariGrupId",
                table: "Cariler",
                column: "CariGrupId",
                principalTable: "CariGruplar",
                principalColumn: "CariGrupId",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Cariler_CariGruplar_CariGrupId",
                table: "Cariler");

            migrationBuilder.Sql("ALTER TABLE \"Cariler\" ALTER COLUMN \"CariGrupId\" TYPE integer USING \"CariGrupId\"::integer;");
            migrationBuilder.Sql("ALTER TABLE \"CariGruplar\" ALTER COLUMN \"CariGrupId\" TYPE integer USING \"CariGrupId\"::integer;");
            migrationBuilder.Sql("ALTER TABLE \"CariGruplar\" ALTER COLUMN \"CariGrupId\" ADD GENERATED BY DEFAULT AS IDENTITY;");

            migrationBuilder.AddForeignKey(
                name: "FK_Cariler_CariGruplar_CariGrupId",
                table: "Cariler",
                column: "CariGrupId",
                principalTable: "CariGruplar",
                principalColumn: "CariGrupId",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
