// <auto-generated />
using EMutabakat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EMutabakat.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319131210_AddAllTables")]
    partial class AddAllTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EMutabakat.Models.Firma", b =>
                {
                    b.Property<int>("FirmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FirmaId"));

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmaAdres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FirmaAktifPasif")
                        .HasColumnType("integer");

                    b.Property<string>("FirmaGsm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmaIl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmaIlce")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmaMail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmaMersisNumarasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmaSmtpHost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmaSmtpPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FirmaSmtpPort")
                        .HasColumnType("integer");

                    b.Property<string>("FirmaSmtpSecure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmaSmtpUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmaTelefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmaUnvan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmaVergiDairesi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmaVergiNumarasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmaWebAdresi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmaYetkiliAdiSoyadi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FirmaId");

                    b.ToTable("Firmalar");
                });
#pragma warning restore 612, 618
        }
    }
}
