// <auto-generated />
using System;
using EMutabakat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EMutabakat.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407083757_AddCurrencyCodesTable")]
    partial class AddCurrencyCodesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EMutabakat.Models.Cari", b =>
                {
                    b.Property<string>("CariId")
                        .HasColumnType("text");

                    b.Property<int>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<string>("CariAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CariAdres")
                        .HasColumnType("text");

                    b.Property<int>("CariAktifPasif")
                        .HasColumnType("integer");

                    b.Property<string>("CariDovizKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CariGrupId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CariIl")
                        .HasColumnType("text");

                    b.Property<string>("CariIlce")
                        .HasColumnType("text");

                    b.Property<string>("CariUnvan")
                        .HasColumnType("text");

                    b.Property<string>("CariVergiDairesi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CariVergiNumarasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CariWebAdresi")
                        .HasColumnType("text");

                    b.Property<string>("CariYetkiliAdiSoyadi")
                        .HasColumnType("text");

                    b.Property<string>("CariYetkiliGsm")
                        .HasColumnType("text");

                    b.Property<string>("CariYetkiliMail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CariYetkiliTelefon")
                        .HasColumnType("text");

                    b.HasKey("CariId", "FirmaId");

                    b.HasIndex("CariDovizKodu");

                    b.HasIndex("CariGrupId");

                    b.HasIndex("FirmaId");

                    b.ToTable("Cariler");
                });

            modelBuilder.Entity("EMutabakat.Models.CariGrup", b =>
                {
                    b.Property<string>("CariGrupId")
                        .HasColumnType("text");

                    b.Property<string>("CariGrupAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FirmaId")
                        .HasColumnType("integer");

                    b.HasKey("CariGrupId");

                    b.HasIndex("FirmaId");

                    b.ToTable("CariGruplar");
                });

            modelBuilder.Entity("EMutabakat.Models.DovizKodu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TCMB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DovizKodlari");
                });

            modelBuilder.Entity("EMutabakat.Models.Firma", b =>
                {
                    b.Property<int>("FirmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FirmaId"));

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmaAdres")
                        .HasColumnType("text");

                    b.Property<int>("FirmaAktifPasif")
                        .HasColumnType("integer");

                    b.Property<string>("FirmaGsm")
                        .HasColumnType("text");

                    b.Property<string>("FirmaIl")
                        .HasColumnType("text");

                    b.Property<string>("FirmaIlce")
                        .HasColumnType("text");

                    b.Property<string>("FirmaMail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmaMersisNumarasi")
                        .HasColumnType("text");

                    b.Property<string>("FirmaSmtpHost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmaSmtpPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FirmaSmtpPort")
                        .HasColumnType("integer");

                    b.Property<string>("FirmaSmtpSecure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmaSmtpUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmaTelefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmaUnvan")
                        .HasColumnType("text");

                    b.Property<string>("FirmaVergiDairesi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmaVergiNumarasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmaWebAdresi")
                        .HasColumnType("text");

                    b.Property<string>("FirmaYetkiliAdiSoyadi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FirmaId");

                    b.ToTable("Firmalar");
                });

            modelBuilder.Entity("EMutabakat.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KullaniciId"));

                    b.Property<int>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KullaniciAktifPasif")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KullaniciGsm")
                        .HasColumnType("text");

                    b.Property<string>("KullaniciMail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KullaniciSoyadi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("KullaniciId");

                    b.HasIndex("FirmaId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("EMutabakat.Models.KullaniciFirma", b =>
                {
                    b.Property<int>("KullaniciFirmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KullaniciFirmaId"));

                    b.Property<int>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.HasKey("KullaniciFirmaId");

                    b.HasIndex("FirmaId");

                    b.HasIndex("KullaniciId", "FirmaId")
                        .IsUnique();

                    b.ToTable("KullaniciFirmalari");
                });

            modelBuilder.Entity("EMutabakat.Models.Mutabakat", b =>
                {
                    b.Property<int>("MutabakatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MutabakatId"));

                    b.Property<string>("CariId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<string>("MutabakatAciklama")
                        .HasColumnType("text");

                    b.Property<decimal>("MutabakatBakiye")
                        .HasColumnType("numeric");

                    b.Property<string>("MutabakatBakiyeTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MutabakatCevapAciklama")
                        .HasColumnType("text");

                    b.Property<string>("MutabakatCevapAdSoyad")
                        .HasColumnType("text");

                    b.Property<string>("MutabakatCevapGsm")
                        .HasColumnType("text");

                    b.Property<string>("MutabakatCevapMail")
                        .HasColumnType("text");

                    b.Property<DateTime?>("MutabakatCevapTarihSaat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("MutabakatDonemi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MutabakatDovizKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MutabakatDurum")
                        .HasColumnType("integer");

                    b.Property<int>("MutabakatGonderimDurumu")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MutabakatGonderimTarihSaat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MutabakatReceiveStoragePath")
                        .HasColumnType("text");

                    b.Property<int>("MutabakatTipi")
                        .HasColumnType("integer");

                    b.Property<string>("MutabakatToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MutabakatId");

                    b.HasIndex("FirmaId");

                    b.HasIndex("MutabakatDovizKodu");

                    b.HasIndex("CariId", "FirmaId");

                    b.ToTable("Mutabakatlar");
                });

            modelBuilder.Entity("EMutabakat.Models.Cari", b =>
                {
                    b.HasOne("EMutabakat.Models.DovizKodu", "DovizKodu")
                        .WithMany()
                        .HasForeignKey("CariDovizKodu")
                        .HasPrincipalKey("TCMB")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMutabakat.Models.CariGrup", "CariGrup")
                        .WithMany()
                        .HasForeignKey("CariGrupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMutabakat.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CariGrup");

                    b.Navigation("DovizKodu");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("EMutabakat.Models.CariGrup", b =>
                {
                    b.HasOne("EMutabakat.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("EMutabakat.Models.Kullanici", b =>
                {
                    b.HasOne("EMutabakat.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("EMutabakat.Models.KullaniciFirma", b =>
                {
                    b.HasOne("EMutabakat.Models.Firma", "Firma")
                        .WithMany("KullaniciFirmalari")
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMutabakat.Models.Kullanici", "Kullanici")
                        .WithMany("KullaniciFirmalari")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("EMutabakat.Models.Mutabakat", b =>
                {
                    b.HasOne("EMutabakat.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMutabakat.Models.DovizKodu", "DovizKodu")
                        .WithMany()
                        .HasForeignKey("MutabakatDovizKodu")
                        .HasPrincipalKey("TCMB")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMutabakat.Models.Cari", "Cari")
                        .WithMany()
                        .HasForeignKey("CariId", "FirmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cari");

                    b.Navigation("DovizKodu");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("EMutabakat.Models.Firma", b =>
                {
                    b.Navigation("KullaniciFirmalari");
                });

            modelBuilder.Entity("EMutabakat.Models.Kullanici", b =>
                {
                    b.Navigation("KullaniciFirmalari");
                });
#pragma warning restore 612, 618
        }
    }
}
